// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObtvApyqU9fMwZC1TxPN-5n6Cx37QdrM',
    appId: '1:482896346764:web:a056331e6eb5e5865d05a9',
    messagingSenderId: '482896346764',
    projectId: 'gishtube-abade',
    authDomain: 'gishtube-abade.firebaseapp.com',
    storageBucket: 'gishtube-abade.firebasestorage.app',
    measurementId: 'G-6JVTMTDFGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfMJQn9nuGH1dkUIPeXNNoLjdBN7LV6s',
    appId: '1:482896346764:android:2038562534941be15d05a9',
    messagingSenderId: '482896346764',
    projectId: 'gishtube-abade',
    storageBucket: 'gishtube-abade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk4spewJlkIGGQhBUegGlcYQO6bfTICTU',
    appId: '1:482896346764:ios:268f889f0e360f485d05a9',
    messagingSenderId: '482896346764',
    projectId: 'gishtube-abade',
    storageBucket: 'gishtube-abade.firebasestorage.app',
    iosClientId: '482896346764-7opa8rf7a1s5ok4oibluotg5vcforjph.apps.googleusercontent.com',
    iosBundleId: 'com.example.gishtube',
  );
}
